# Site settings
title: Sam David
email: sfd1987@gmail.com
description: "Student Web Developer, Currently in Austin TX!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: The_Bear_Jeww
github_username:  sfd1987

# Build settings
markdown: kramdown
permalink: pretty
