# Site settings
title: Sam David
email: sfd1987@gmail.com
description: "An awesome blog for a student in web development"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  sfd1987

# Build settings
markdown: kramdown
permalink: pretty
